# Generated by Django 2.1.1 on 2018-09-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='poster_sexuality',
            field=models.CharField(choices=[('s', 'Heterosexual'), ('g', 'Homosexual'), ('b', 'Bisexual'), ('a', 'Asexual'), ('d', 'Dog Fucker'), ('o', 'Other'), ('u', 'Unknown')], max_length=1),
        ),
    ]
