# Generated by Django 2.1.1 on 2018-09-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180923_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='face',
            name='parameters',
            field=models.TextField(blank=True, default=''),
        ),
    ]
